version: '3.8'

services:
  # api:
  #   container_name: api
  #   build: .
  #   ports:
  #     - 3000:3000
  #   networks:
  #     - angola-network
  #   restart: on-failure
  #   depends_on:
  #     - redis

  db:
    container_name: mysql
    image: mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    ports:
      - 3306:3306
    volumes:
      - ./mysql:/var/lib/mysql
# networks:
#   todos-network:
#     driver: bridge
